// Lightweight report builder. Emits JSON and/or Markdown with a consistent
// header.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { VERSION } from './version.mjs';

export class Report {
  constructor({ title, command }) {
    this.title = title;
    this.command = command;
    this.generatedAt = new Date().toISOString();
    this.sections = [];           // { heading, rows: [{...}] }
    this.counts = {};             // { label: n }
    this.summary = {};
  }

  addSection(heading) {
    const s = { heading, rows: [] };
    this.sections.push(s);
    return s;
  }

  addRow(section, row) { section.rows.push(row); }

  addCount(label, n) { this.counts[label] = (this.counts[label] ?? 0) + n; }

  setSummary(obj) { this.summary = { ...this.summary, ...obj }; }

  toJSON() {
    return {
      title: this.title,
      command: this.command,
      generated_at: this.generatedAt,
      toolkit_version: VERSION,
      summary: this.summary,
      counts: this.counts,
      sections: this.sections,
    };
  }

  toMarkdown() {
    const lines = [];
    lines.push(`# ${this.title}`);
    lines.push('');
    lines.push(`_generated by tailwind-cleanup v${VERSION} • ${this.generatedAt}_`);
    if (this.command) lines.push(`_command: \`${this.command}\`_`);
    lines.push('');

    if (Object.keys(this.summary).length) {
      lines.push('## Summary');
      lines.push('');
      for (const [k, v] of Object.entries(this.summary)) {
        lines.push(`- **${k}**: ${formatValue(v)}`);
      }
      lines.push('');
    }

    if (Object.keys(this.counts).length) {
      lines.push('## Counts');
      lines.push('');
      const entries = Object.entries(this.counts).sort((a, b) => b[1] - a[1]);
      for (const [k, n] of entries) lines.push(`- ${k}: **${n}**`);
      lines.push('');
    }

    for (const s of this.sections) {
      if (!s.rows.length) continue;
      lines.push(`## ${s.heading}`);
      lines.push('');
      const keys = Array.from(new Set(s.rows.flatMap(r => Object.keys(r))));
      if (keys.length) {
        lines.push(`| ${keys.join(' | ')} |`);
        lines.push(`| ${keys.map(() => '---').join(' | ')} |`);
        for (const row of s.rows) {
          lines.push(`| ${keys.map(k => formatCell(row[k])).join(' | ')} |`);
        }
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  writeJson(path) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, JSON.stringify(this.toJSON(), null, 2));
  }

  writeMarkdown(path) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, this.toMarkdown());
  }

  write(dir, basename, formats /* 'json' | 'md' | 'both' */) {
    const want = formats === 'both' ? ['json', 'md'] : [formats];
    if (want.includes('json')) this.writeJson(`${dir}/${basename}.json`);
    if (want.includes('md')) this.writeMarkdown(`${dir}/${basename}.md`);
  }
}

function formatValue(v) {
  if (v == null) return '';
  if (typeof v === 'object') return '`' + JSON.stringify(v) + '`';
  return String(v);
}

function formatCell(v) {
  if (v == null) return '';
  if (typeof v === 'string') return v.replace(/\|/g, '\\|');
  return String(v);
}
