#!/usr/bin/env node
// audit/class-strings.mjs
//
// Per-file inventory of every Tailwind class string in the project, including
// strings that live outside `className=…`. Catches:
//
//   - className="…" and className={…} expression bodies
//   - clsx / cn / classnames / twMerge call arguments
//   - tv(…) and cva(…) configuration objects (slots, variants, base, etc.)
//   - tw`…` tagged template literals
//   - *CLASS / *Class local string constants
//
// Emits two artefacts in TW_CLEANUP_REPORTS_DIR (default
// `tailwind-cleanup-reports/`):
//
//   class-strings.json  — full structured listing, ideal for downstream tools
//   class-strings.md    — human-readable per-file dump matching the
//                          shape `Formula.tsx: [ '…', '…', … ]`
//
// Exit code 0 (audit only).

import { readFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { bootstrap, collectFiles } from '../lib/script-runtime.mjs';
import { Report } from '../lib/report.mjs';
import { extractClassStrings, normaliseClassString } from '../lib/class-strings.mjs';

const { cfg } = bootstrap();
const files = collectFiles(cfg);
const cwd = cfg.__cwd ?? process.cwd();

const perFile = []; // { path, strings: [{ line, context, value }] }
const contextTotals = new Map();
let totalStrings = 0;

for (const path of files) {
  let src;
  try { src = readFileSync(path, 'utf8'); } catch { continue; }

  const occurrences = extractClassStrings(src);
  if (occurrences.length === 0) continue;

  const rel = relative(cwd, path);
  const strings = occurrences.map(o => ({
    line: o.line,
    context: o.context,
    value: normaliseClassString(o.value),
  }));

  perFile.push({ path: rel, strings });
  totalStrings += strings.length;
  for (const s of strings) contextTotals.set(s.context, (contextTotals.get(s.context) ?? 0) + 1);
}

// Sort: most strings first, then by path.
perFile.sort((a, b) => b.strings.length - a.strings.length || a.path.localeCompare(b.path));

const r = new Report({ title: 'Tailwind class-string inventory', command: 'audit:classes' });
r.setSummary({
  files_scanned: files.length,
  files_with_strings: perFile.length,
  total_strings: totalStrings,
});
for (const [ctx, n] of [...contextTotals.entries()].sort((a, b) => b[1] - a[1])) {
  r.addCount(ctx, n);
}

// Default markdown rendering would emit one row per string. Instead, render a
// custom listing that groups by file in the requested `path: [ … ]` shape.
const customMarkdown = renderMarkdown(r, perFile);

// JSON path: include the per-file structure directly under `files`.
const reportJson = {
  ...r.toJSON(),
  files: perFile,
};

const dir = process.env.TW_CLEANUP_REPORTS_DIR ?? resolve(cwd, cfg.reports?.dir ?? 'tailwind-cleanup-reports');
const fmt = process.env.TW_CLEANUP_REPORT ?? 'both';

import('node:fs').then(({ mkdirSync, writeFileSync }) => {
  mkdirSync(dir, { recursive: true });
  if (fmt === 'json' || fmt === 'both') {
    writeFileSync(`${dir}/class-strings.json`, JSON.stringify(reportJson, null, 2));
  }
  if (fmt === 'md' || fmt === 'both') {
    writeFileSync(`${dir}/class-strings.md`, customMarkdown);
  }
  console.log(`audit:classes — ${totalStrings} class strings across ${perFile.length} files (of ${files.length} scanned). Report: ${dir}/class-strings.{json,md}`);
});

function renderMarkdown(report, files) {
  const lines = [];
  lines.push(`# ${report.title}`);
  lines.push('');
  lines.push(`_generated by tailwind-cleanup • ${report.generatedAt}_`);
  lines.push(`_command: \`${report.command}\`_`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  for (const [k, v] of Object.entries(report.summary)) lines.push(`- **${k}**: ${v}`);
  lines.push('');

  if (Object.keys(report.counts).length) {
    lines.push('## Counts by context');
    lines.push('');
    const entries = Object.entries(report.counts).sort((a, b) => b[1] - a[1]);
    for (const [k, n] of entries) lines.push(`- ${k}: **${n}**`);
    lines.push('');
  }

  lines.push('## Strings by file');
  lines.push('');
  for (const { path, strings } of files) {
    lines.push(`### ${path} (${strings.length})`);
    lines.push('');
    lines.push('```');
    lines.push('[');
    for (let i = 0; i < strings.length; i++) {
      const s = strings[i];
      const quote = s.value.includes("'") ? '"' : "'";
      const trailingComma = i === strings.length - 1 ? '' : ',';
      lines.push(`  ${quote}${s.value}${quote}${trailingComma}  // L${s.line} ${s.context}`);
    }
    lines.push(']');
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}
